services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: isapre-frontend
    ports:
      - "3001:8080"
    environment:
      # ðŸ”— URL de tu Backend (usa localhost si corre local o la URL de GCP si ya estÃ¡ arriba)
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:3000}
      - NEXT_TELEMETRY_DISABLED=1
    restart: always

# Nota: No necesitamos volÃºmenes de base de datos aquÃ­ ya que el Frontend es Stateless.